---
- hosts: app:frontend
  remote_user: ubuntu

  tasks:
    - name: Test
      command: touch /home/ubuntu/artifacts/test.file
    - name: Install python3
      become: true
      command: apt install python3 -y
    - name: Download pip
      command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - name: Install pip
      command: python3 get-pip.py --user
    - name: install all dependencies
      command: python3 -m pip install -I lxml --user
    - name: install java
      become: true
      apt:
        update_cache: yes
        name: openjdk-8-jre
    - name: Download artifact from Nexus
      maven_artifact:
        artifact_id: devops-training-backend
        dest: /home/ubuntu/artifacts
        extension: jar
        group_id: by.brest.project
        password: "{{ nexus_password }}"
        repository_url: "https://nexus-solodukha.test.coherentprojects.net/repository/devops"
        username: "{{ nexus_username }}"
        version: 36
    - name: Start application
      command: "java -jar ./artifacts/devops-training-backend-36.jar &"
