---
- hosts: frontend
  remote_user: ubuntu
  vars:
  - ansible_python_interpreter: "{{ '/usr/bin/python3' }}"
  tasks:
  - name: Test
    command: touch /home/ubuntu/artifacts/test.file
  - name: Install python3
    become: yes
    command: apt install python3 -y
  - name: Download pip
    command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - name: Install pip
    command: python3 get-pip.py --user
  - name: install all dependencies
    command: python3 -m pip install -I lxml --user
  - name: add repository
    shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    become: yes
  - name: install npm
    become: yes
    apt:
      update_cache: yes
      name: nodejs
  - name: Install serve
    shell: npm install -g serve
    become: yes
  - name: Download artifact from Nexus
    maven_artifact:
      artifact_id: devops-training-frontend
      dest: /home/ubuntu
      extension: tar
      group_id: by.brest.project
      password: "{{ nexus_password }}"
      repository_url: "https://nexus-solodukha.test.coherentprojects.net/repository/training"
      username: "{{ nexus_username }}"
      version: "{{ artifact_version }}"
  - name: Find working application PID
    shell: ps -au | grep "node" | grep -v "grep" | grep -P -o "[[:digit:]]*" | head -n 1
    register: app_pid
  - name: Stop previous application
    shell: kill app_pid
    when: app_pid.stdout != ""
  - name: Clean
    shell: rm -rf ./build
  - name: Prepare
    shell: tar -xf devops-training-frontend-{{ artifact_version }}.tar
  - name: Start application
    shell: nohup serve -s ./build &
