---
- hosts: backend
  remote_user: ubuntu

  tasks:
    - name: Test
      command: touch /home/ubuntu/artifacts/test.file
    - name: Install python3
      become: yes
      command: apt install python3 -y
    - name: Download pip
      command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - name: Install pip
      command: python3 get-pip.py --user
    - name: install all dependencies
      command: python3 -m pip install -I lxml --user
    - name: install java
      become: yes
      apt:
        update_cache: yes
        name: openjdk-8-jre
    - name: Download artifact from Nexus
      maven_artifact:
        artifact_id: devops-training-backend
        dest: /home/ubuntu/artifacts
        extension: jar
        group_id: by.brest.project
        password: "{{ nexus_password }}"
        repository_url: "https://nexus-solodukha.test.coherentprojects.net/repository/training"
        username: "{{ nexus_username }}"
        version: "{{ artifact_version }}"
    - name: Find working application PID
      shell: ps -au | grep "java -jar" | grep -v "grep" | grep -P -o "[[:digit:]]*" | head -n 1
      register: app_pid
    - name: Stop previous application
      shell: kill app_pid
      when: app_pid.stdout != ""
    - name: Start application
      shell: nohup java -jar ./artifacts/devops-training-backend-{{ artifact_version }}.jar &
