---
- hosts: app:frontend
  remote_user: ubuntu

  tasks:
  - name: Download artifact from Nexus
    maven_artifact:
      artifact_id: devops-training-backend
      dest: /tmp/backend-artifact.zip
      extension: zip
      group_id: by.brest.project
      password: {{ nexus_password }}
      repository_url: https://nexus-solodukha.test.coherentprojects.net
      username: {{ nexus_username }}
      version: 36